using System.Collections.Generic;
using CommandLine;
using SevenZip;
using Sewer56.Update.Tool.Options.Groups;

namespace Sewer56.Update.Tool.Options;

[Verb("CreateRelease", HelpText = "Creates a new release.")]
internal class CreateReleaseOptions : ICreateReleaseOptions
{
    public string ExistingPackagesPath { get; set; }

    public string OutputPath { get; set; }

    public string PackageName { get; set; }

    public Archiver Archiver { get; set; }

    public int MaxParallelism { get; set; }
    
    public bool AutoGenerateDelta { get; set; } = false;

    public bool DontAppendVersionToPackages { get; set; } = false;

    /* SharpCompress Specific */
    public SharpCompressFormat SharpCompressFormat { get; set; }

    /* NuGet Specific */
    public string NuGetId { get; set; }
    public string NuGetDescription { get; set; }
    public IEnumerable<string> NuGetAuthors { get; set; }

    /* SevenZipSharp Specific */
    public OutArchiveFormat SevenZipSharpArchiveFormat { get; set; }
    public CompressionLevel SevenZipSharpCompressionLevel { get; set; }
    public CompressionMethod SevenZipSharpCompressionMethod { get; set; }
}

public enum Archiver
{
    Zip,
    NuGet,
    SharpCompress,
    SevenZipSharp
}