using System.Collections.Generic;
using CommandLine;
using SevenZip;
using Sewer56.Update.Tool.Options.Groups;

namespace Sewer56.Update.Tool.Options;

[Verb("CreateRelease", HelpText = "Creates a new release.")]
internal class CreateReleaseOptions : ISharpCompressOptions, INuGetOptions, ISevenZipSharpOptions
{
    public const int DefaultInt = -1;

    [Option(Required = false, HelpText = "Path to a text file with file paths to existing packages (1 path per line). Paths should point to uncompressed folders.")]
    public string ExistingPackagesPath { get; internal set; }

    [Option(Required = true, HelpText = "The folder where to save the new release. If there is already a release in that folder, it will be updated.")]
    public string OutputPath { get; internal set; }

    [Option(Required = false, HelpText = "The name for the packages as downloaded by the user.", Default = "Package")]
    public string PackageName { get; internal set; }

    [Option(Required = false, HelpText = "The archiver to use for archiving the content.", Default = Archiver.Zip)]
    public Archiver Archiver { get; internal set; }

    [Option(Required = false, HelpText = "Maximum number of parallel compression tasks.", Default = DefaultInt)]
    public int MaxParallelism { get; internal set; }
    
    [Option(Required = false, HelpText = "If updating existing release, auto generates delta package from last version to current version.", Default = false)]
    public bool AutoGenerateDelta { get; internal set; } = false;

    /* SharpCompress Specific */
    public SharpCompressFormat SharpCompressFormat { get; set; }

    /* NuGet Specific */
    public string NuGetId { get; set; }
    public string NuGetDescription { get; set; }
    public IEnumerable<string> NuGetAuthors { get; set; }

    /* SevenZipSharp Specific */
    public OutArchiveFormat SevenZipSharpArchiveFormat { get; set; }
    public CompressionLevel SevenZipSharpCompressionLevel { get; set; }
    public CompressionMethod SevenZipSharpCompressionMethod { get; set; }
}

public enum Archiver
{
    Zip,
    NuGet,
    SharpCompress,
    SevenZipSharp
}